
// ═══════════════════════════════════════════════
// GAME DATA
// ═══════════════════════════════════════════════
const BANDS = [
  { id:'b01', name:'The Hollow Saints', genre:'Post-Punk', genreKey:'punk',
    bio:"Four-piece. We've been told we're 'difficult'. We prefer 'uncompromising'. Touring the north this autumn — looking for the right rooms.",
    traits:['Road Warriors','Underground Cred','Pyro Enthusiasts'], fee:'££', feeVal:180,
    agent:'Liz Carrow @ Ironclad', fame:1, fans:40 },
  { id:'b02', name:'Coral Vestiges', genre:'Indie Folk', genreKey:'folk',
    bio:"Fingerpicking and field recordings. We play quiet rooms and ask that you do too. Our last EP got a feature in The Wire.",
    traits:['Acoustic Purists','Industry Darlings','Punctual'], fee:'££', feeVal:150,
    agent:'Theo Marsh @ Quiet Storm', fame:1, fans:35 },
  { id:'b03', name:'NIGHTMARKET', genre:'Synthwave', genreKey:'electronic',
    bio:"Neon. Nostalgia. Drum machines. We've played every warehouse in this city — now we want a stage with a roof.",
    traits:['Face Paint','Merch Machine','Party Animals'], fee:'£££', feeVal:250,
    agent:'Dana Cole @ Static Frequency', fame:2, fans:80 },
  { id:'b04', name:'Gravel & Glass', genre:'Blues Rock', genreKey:'rock',
    bio:"We've been doing this since before you were born, son. Ask your parents.",
    traits:['Road Warriors','Punctual','Crowd Surfers'], fee:'££', feeVal:160,
    agent:'Jim Rowe @ Blacktop', fame:1, fans:50 },
  { id:'b05', name:'Seraph System', genre:'Noise Rock', genreKey:'punk',
    bio:"Loud. Confrontational. Probably not for everyone — which is the point.",
    traits:['Drama Queens','Uncompromising','Always Late'], fee:'£', feeVal:80,
    agent:'Self-managed', fame:0, fans:12 },
  { id:'b06', name:'Milk & Fever', genre:'Dream Pop', genreKey:'pop',
    bio:"We make the kind of music you put on when you can't sleep. Hazy. Layered. True.",
    traits:['Rising Stars','Method Actors','Label Pressure'], fee:'££', feeVal:200,
    agent:'Cass Reid @ Bloom', fame:1, fans:60 },
  { id:'b07', name:'Iron Gospel', genre:'Metal', genreKey:'metal',
    bio:"We don't do half measures. Pyro, volume, and conviction. Book us or don't.",
    traits:['Pyro Enthusiasts','Crowd Surfers','Drama Queens'], fee:'£££', feeVal:280,
    agent:'Rick Voss @ Hammer', fame:2, fans:90 },
  { id:'b08', name:'The Picket Line', genre:'Garage Punk', genreKey:'punk',
    bio:"Political. Loud. Cheap. Playing every toilet venue in the country. Proudly.",
    traits:['Local Heroes','Underground Cred','Always Late'], fee:'£', feeVal:60,
    agent:'Self-managed', fame:0, fans:20 },
  { id:'b09', name:'Sable & Rust', genre:'Post-Rock', genreKey:'rock',
    bio:"Instrumental. Cinematic. We build slowly. Give us a room with good acoustics and we'll give you something you won't forget.",
    traits:['Acoustic Purists','Method Actors','Punctual'], fee:'££', feeVal:170,
    agent:'Theo Marsh @ Quiet Storm', fame:1, fans:45 },
  { id:'b10', name:'DJ ZOETROPE', genre:'Electronic', genreKey:'electronic',
    bio:"One decks. Infinite genres. I've played to 3 people and 3000. Both are fine.",
    traits:['Chameleons','Merch Machine','Party Animals'], fee:'££', feeVal:140,
    agent:'Dana Cole @ Static Frequency', fame:1, fans:55 },
  { id:'b11', name:'Amber Frequency', genre:'Psych Rock', genreKey:'rock',
    bio:"Two drummers. One vision. Currently between labels and loving it.",
    traits:['Face Paint','Crowd Surfers','Rising Stars'], fee:'££', feeVal:190,
    agent:'Liz Carrow @ Ironclad', fame:1, fans:48 },
  { id:'b12', name:'The Ledger', genre:'Acoustic Soul', genreKey:'folk',
    bio:"Just the songs. No effects. No production. Just us and the room.",
    traits:['Acoustic Purists','Uncompromising','Industry Darlings'], fee:'£', feeVal:90,
    agent:'Self-managed', fame:0, fans:15 },
  { id:'b13', name:'Low Coven', genre:'Shoegaze', genreKey:'rock',
    bio:"Walls of reverb. Velvet dynamics. We need smoke or we don't play.",
    traits:['Method Actors','Underground Cred','Smoke Lovers'], fee:'££', feeVal:160,
    agent:'Theo Marsh @ Quiet Storm', fame:1, fans:38 },
  { id:'b14', name:'Volt Temple', genre:'Industrial', genreKey:'metal',
    bio:"Machines. Noise. Intent. We've worked with three different lighting designers. They all quit.",
    traits:['Pyro Enthusiasts','Drama Queens','Face Paint'], fee:'£££', feeVal:300,
    agent:'Rick Voss @ Hammer', fame:2, fans:70 },
];
